version: "3"
# set .env vars: TZ, DOMAIN_NAME, SITE_PATH
# .env: MAILMANAGER
# IPv4 only
# docker network create proxy_default --subnet "192.168.100.0/24"
# IPv4/IPv6 network
# docker network create proxy_default --ipv6 --subnet "fd00:0000:0000:0000::/64"

networks:
  proxy_default:
    external: true

services:
  duplicati:
    image: lscr.io/linuxserver/duplicati:latest
    container_name: duplicati
    environment:
      - PUID=1001
      - PGID=1001
      - TZ
      - CLI_ARGS
    volumes:
      - config:/config
      - backups:/backups
      - source:/source:ro
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy_default
      - traefik.http.services.${SITE_PATH}.loadbalancer.server.port=8200
      - traefik.http.routers.${SITE_PATH}.tls.certresolver=letsencrypt
      - traefik.frontend.entryPoints=http,https
      - traefik.http.routers.${SITE_PATH}.rule=Host(`${DOMAIN_NAME}`) && PathPrefix("/${SITE_PATH}")
      - traefik.http.middlewares.${SITE_PATH}.stripprefix.prefixes="/${SITE_PATH}"


    networks: 
      - proxy_default
  
volumes:
  config:
    driver_opts:
      type: none
      device: ${VOL_DUPLICATI}
      o: bind
  backups:
    driver_opts:
      type: none
      device: ${VOL_BACKUP}
      o: bind
  source:
    driver_opts:
      type: none
      device: ${VOL_SOURCE}
      o: bind
