name: Docker Compose Up for Production

on:
  push:
    branches: [ production ]

jobs:
  run:
    runs-on: self-hosted
    env:
      SITE_PATH: ${{ secrets.BACKUP_PATH }}
      DOMAIN_NAME: ${{ secrets.BACKUP_URL }}
      VOL_DUPLICATI: ${{ secrets.VOL_DUPLICATI }}
      VOL_BACKUP: ${{ secrets.VOL_BACKUP }}
      VOL_SOURCE: ${{ secrets.VOL_SOURCE }}
    steps:
      - uses: actions/checkout@v3

      #- name: Login to Docker Hub (optional)
      #  run: |
      #    echo "$DOCKER_HUB_USERNAME:$DOCKER_HUB_PASSWORD" | docker login --username --password-stdin

      - name: Update Docker Compose
        if: always()
        run: docker compose pull

      - name: Stop Docker Compose
        if: always()
        run: docker compose down --remove-orphans -v
        
      - name: Run Docker Compose Up
        run: docker compose up -d --wait
